fisrt_integer = int(input())
second_integer = int(input())
third_integer = int(input())
forth_integer = int(input())
summery = (((fisrt_integer + second_integer) // third_integer) * forth_integer)
print(summery)
